### ISSUE TITLE
Unable to set mail server user name

### ISSUE THREAD

**Issue by tvvocold** [ctron/package-drone-openshift#1]
i had login as admin and try its own mail sending test, but cannot got email (in inbox or spam box).so i try to use mailgun's free account , but the user and passwd value  seems cannot change after i click update(the user value back to admin every time)

**Comment by ctron** [comment]
Did you use the setup of OpenShift?

**Comment by tvvocold** [comment]
yup

**Comment by ctron** [comment]
So there is no need to enter anything special for openshift. The default setup will work.

In which field do you have the value "admin"? Maybe you can attach a screenshot and give the last few steps to reproduce this issue.

**Comment by tvvocold** [comment]
http://imgur.com/bD19Tr8 when i click updata it become 
![image](https://cloud.githubusercontent.com/assets/4530539/6545413/da070eb2-c5c0-11e4-8e49-3f6a2108a2c7.png)

**Comment by tvvocold** [comment]
and seems the Reset button didn't work either.  nothing happened when i click it.

**Comment by ctron** [comment]
So when you pressed update it worked?

**Comment by tvvocold** [comment]
nope,the user value turn blank when i click update

**Comment by ctron** [comment]
Ok so I just checked with a fresh instance created on OpenShift.
- There is a bug in Package Drone for the username field, this will be fixed in the next Package Drone version
- Sending e-mails with the initial configuration works
- The reset button works as well, resetting to what was last stored in the configuration

So maybe you wait for the next version and give it another try.

Thanks

**Comment by ctron** [comment]
Ok, so this bug is fixed and can be tested by using the "next" version of the cartridge, since this is a pre-release the moment (0.3.0.rc2).

The instructions on how to use "next" are at: https://github.com/ctron/package-drone-openshift#using-next

**Comment by ctron** [comment]
Ok, this looks good to me. I would kindly ask you to re-test with the "next" branch.

**Comment by tvvocold** [comment]
i try new branch, still cannot work with both default mail or mailgun' setting.
Mailgun' 

```
User  rpm
Password ******
Host smtp.mailgun.org
Port 25
...
```

error when testing email.

```
Test message failed! 550 5.7.1 Relaying denied
```

**Comment by ctron** [comment]
Well but that is a problem with your mail provider, not allowing relaying, would suspect.

Did you try with a new machine and the defaults, before making any modifications.

**Comment by tvvocold** [comment]
i retest it by recreate the app.so i don't think the new machine or openshift account will work :)

**Comment by ctron** [comment]
Well all tests with the default settings work. I cannot imagine that your openshift machine gets a different setup at the OS level.

And for the relay denied situation I am pretty sure that this has to do with your mail provider. Does your account allow relaying?

**Comment by tvvocold** [comment]
Sure, that's what mailgun' do, and i test it in app like owncloud or mail.

**Comment by ctron** [comment]
OK, I will try to test with such an account.

**Comment by ctron** [comment]
Can you please to me a favor. Create a new machine & app, don't change the default mail settings and send a test message. If it does not show up, please check the maillog and mailqueue on the machine itself. That would be very helpful!

**Comment by ctron** [comment]
Ok, so using a test account from mailgun I can reproduce this issue locally! I hope to have a fix today. I will let you know.

Thanks for helping me!

**Comment by tvvocold** [comment]
hi @ctron ,is this issue fixed? 
btw, supported rpm?

**Comment by ctron** [comment]
Yes, this issue is fixed. For OpenShift you will need to create a new instance.

RPM support is still missing (please see or subscribe to https://github.com/ctron/package-drone/issues/16). If you know somebody who can help out, I am glad to give you a start.

**Comment by tvvocold** [comment]
I think maybe [he](https://github.com/evilkost) can help u. Maybe..

**Comment by ctron** [comment]
Hi, yes sure. Just ask him, if he needs some help just let me know.
